version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: innopilot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: innopilot
      POSTGRES_PASSWORD: innopilot_password
      POSTGRES_DB: innopilot_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - innopilot-network

networks:
  innopilot-network:
    driver: bridge

volumes:
  postgres_data:
